force-app/main/default/objects/BuyerRequestQuoteInputRepresentation__c/BuyerRequestQuoteInputRepresentation__c.object-meta.xml
<CustomObject>
    <label>Buyer Request Quote Input Representation</label>
    <nameField>
        <displayFormat>BRQIR-{00000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buyer Request Quote Input Representation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BuyerRequestQuoteInputRepresentation__c/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cart</label>
    <referenceTo>WebCart</referenceTo>
    <relationshipLabel>Buyer Request Quote Input Representation</relationshipLabel>
    <relationshipName>Buyer_Request_Quote_Input_Representation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BuyerRequestQuoteInputRepresentation__c/fields/JSON__c.field-meta.xml
<CustomField>
    <fullName>JSON__c</fullName>
    <label>JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BuyerRequestQuoteInputRepresentation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BuyerRequestQuoteRecordWriterInvocabale.cls
public class BuyerRequestQuoteRecordWriterInvocabale {
    @InvocableMethod(label = 'Buyer Request Quote Record Writer' iconName='slds:custom:custom67')
    public static List<ToObjectResult> toObject( List<ToObjectRequest> requests ) {
        
        List<ToObjectResult> results = new List<ToObjectResult>();
        
        List<BuyerRequestQuoteInputRepresentation__c> brqirs = new List<BuyerRequestQuoteInputRepresentation__c>();

        for (Integer r = 0; r < requests.size(); r++) {

            ToObjectRequest request = requests[r];

            BuyerRequestQuoteInputRepresentation__c brqir = new BuyerRequestQuoteInputRepresentation__c();

            Map<String,Object> jsonCart = new Map<String,Object>();

            WebCart cart = [SELECT Id,
                                    AccountId,
                                    Contact__c,
                                    OwnerId,
                                    WebStoreId,
                                    PoNumber,
                                    BillingStreet,
                                    BillingCity,
                                    BillingState,
                                    BillingPostalCode,
                                    BillingCountry,
                                    BillingLatitude,
                                    BillingLongitude
                                    //,CurrencyIsoCode
                                FROM WebCart 
                                WHERE Id = :request.cartId  
                                LIMIT 1
            ];

            Id cartDeliveryGroupId = [SELECT Id FROM CartDeliveryGroup WHERE CartId = :cart.Id][0].Id;
            
            List<CartItem> cartItems = [SELECT
                                            AdjustmentAmount,
                                            Product2Id,
                                            Type,
                                            Quantity,
                                            ListPrice,
                                            SalesPrice,
                                            TotalLineAmount
                                        FROM CartItem 
                                        WHERE CartDeliveryGroupId = :cartDeliveryGroupId];

            jsonCart.put('Id',request.cartId);

            jsonCart.put('AccountId',cart.AccountId);
            jsonCart.put('Contact__c',cart.Contact__c);
            jsonCart.put('OwnerId',cart.OwnerId);
            jsonCart.put('WebStoreId',cart.WebStoreId);
            jsonCart.put('cartItems',cartItems);
            
            brqir.Cart__c = request.cartId;
            brqir.JSON__c = JSON.serialize(jsonCart);
            brqir.Status__c = 'Draft';
            brqirs.add(brqir);

            ToObjectResult response = new ToObjectResult();
            response.inputRepresentationID = brqir.Id;
            results.add(response);

        }

        insert brqirs;

        return results;

    }

    public class ToObjectRequest {

        @InvocableVariable(
            label = 'Cart Id'
            required=true
         )
        public ID cartId;

    }

    public class ToObjectResult {

        @InvocableVariable( 
            label = 'Output String'
        )
        public ID inputRepresentationID;

    }

}